RTCError: Make "message" optional and be the last argument.
Assuming https://github.com/w3c/webrtc-pc/issues/2111 is resolved.
If it is, I'll land this.

Bug: 937844
Change-Id: I7ad149f47fb394f15055cc8fd77e79b4e5e0f317